### ISSUE TITLE
Long term plans?

### ISSUE THREAD

**Issue by enragedginger** [feldi/clj-tf#1]
Hey hi hey,

What are the long term plans for this project? With the release of the Java Tensorflow API, we've started working on a project with similar goals over [here](https://github.com/enragedginger/tensorflow-clj). If we're looking to essentially build the same library, I'd be interested in merging projects so as to unify the community and build a more stable library.

**Comment by feldi** [comment]
Hello from Germany!
Before I started my own project, I looked for other similar projects and found yours, but by that time it seemed dead. Glad to hear that you continue your work on that.
My own project is just a hobby project, done in my spare time to dig deeper into ML, tensorflow, and Clojure.
I have no problem with the idea to abandon my own project and join forces with you. Would you allow me to contribute to your  lib?
If you look at my project, there are some ideas in it that could be interesting for your lib, too, like:
the way I include the native tensorFlow library (see my project.clj), automated generating of tensorflow operations, the "clojurish" API (e.g. Keywords and Maps as args) , the operation name scope etc. 

As to using protobuf in clojure: like I do, use org.clojars.ghaskins/protobuf "3.0.2-2", that is alive and up-to-date.

Cheers,
Peter

**Comment by enragedginger** [comment]
That's great to hear! I've added you to tensorflow-clj, so you should be able to push feature branches directly to the repo and submit PRs without having to fork the project. We're using the Clojurians Slack instance. You can sign up here: https://clojurians.slack.com/ and now that there's more than two of us working on this endeavor, we've created a #tensorflow Slack channel on that instance. After you join, we can discuss more of the long term project vision, dev standards, and how we plan on dividing up the work.

Thanks for the tips on the protobuf stuff. I spent the better part of an evening last week going through the different forks for both lein-protobuf and clojure-protobuf. After rewriting the lein-protobuf plugin, I realized that I didn't even need to compile proto files--I could just use the precompiled TF protobuf JAR. Next, I managed to find the ghaskins fork of clojure-protobuf and started putting it to good use. Because of these dependency overlaps between the DSL I'm currently working on and the stuff you've already written, I've taken the liberty of pushing my partial work out to master so that we don't have conflicts later after you start merging in your current work.

Anyhow, that's an earful, but I'll see you on Slack! Thanks again!

**Comment by feldi** [comment]
Hi,
I am new to slack, and cant just sign in. Maybe you have to invite me there to join the #tensorflow clojurians.slack.com channel? At least it is saying that a team administrator has to invite my email address peter.feldtmann@gmail.com.
Thanks.

**Comment by enragedginger** [comment]
Oh, sorry about that. It looks like you can signup here: http://clojurians.net/
